name: Update GitHub Streak Image

on:
  schedule:
    - cron: '0 0 * * *'  # every day
  workflow_dispatch:

jobs:
  fetch-streak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies (rsvg-convert)
        run: sudo apt-get update && sudo apt-get install -y librsvg2-bin

      - name: Download GitHub Streak SVG
        run: |
          mkdir -p assets
          curl -L "https://streak-stats.demolab.com?user=hsajid-cs&theme=radical&hide_border=true" -o assets/github-streak.svg

      - name: Convert SVG to PNG
        run: |
          rsvg-convert -o assets/github-streak.png assets/github-streak.svg

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/github-streak.png
          git diff --cached --quiet || git commit -m "Update GitHub streak image"
          git push
